# Generated by Django 3.1.1 on 2020-09-28 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='صورة  شخصية '),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='الاسم :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='price',
            field=models.IntegerField(default=0, verbose_name=' سعر الكشف '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='who_i',
            field=models.TextField(default='', max_length=200, verbose_name=' من انا : '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
