# Generated by Django 3.1.1 on 2020-09-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200928_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(default=10, null=True, verbose_name=' سعر الكشف '),
        ),
    ]
