# Generated by Django 3.1.1 on 2020-09-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200927_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='الاسم :'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(default='', verbose_name=' سعر الكشف '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_i',
            field=models.TextField(default='', max_length=200, verbose_name=' من انا : '),
            preserve_default=False,
        ),
    ]
